services:

  db:
    image: postgres:16-alpine
    container_name: pg-letschat-api
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  migrate:
    image: migrate/migrate
    container_name: letschat-api-migrate
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command:
      ["-path", "/migrations", "-database=${LETSCHAT_API_DB_DSN}", "up"]
    depends_on:
      - db
    networks:
      - app_network

  letschat-api:
    build:
      context: .
    image: usman243/letschat-api:latest
    container_name: letschat-api
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8080:8080"
    entrypoint: ["./letschat-api", "-db-dsn=${LETSCHAT_API_DB_DSN}", "-smtp-host=${SMTP_HOST}", "-smtp-port=${SMTP_PORT}", "-smtp-username=${SMTP_USERNAME}", "-smtp-password=${SMTP_PASSWORD}", "-smtp-sender=${SMTP_SENDER}"]
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:
    name: pg_data

networks:
  app_network:
    name: app_network