name: Greenlight_CICD_Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
    paths-ignore:
      - 'cmd/letschat/**'
      - 'internal/client/**'
      - 'internal/tui/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
    paths-ignore:
      - 'cmd/letschat/**'
      - 'internal/client/**'
      - 'internal/tui/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Cleanup workspace
        run: sudo rm -rf ${{ github.workspace }}/*

      - uses: actions/checkout@v4

      - name: Remove old env files
        run: rm -f .env .envrc || true

      - name: Create .env & .envrc file
        run: |
          echo "${{ secrets.ENV }}" >> .env

      - name: Rebuild & Restart using docker compose
        run: |
          if ! sudo docker-compose up -d --build; then
            echo "Docker Compose failed"
            exit 1
          fi

      - name: Notify on success
        if: success()
        run: echo "Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: echo "Deployment failed!"
